import Armchairs from "@/shared/ui/Armchairs";
import Cart from "@/shared/ui/Cart";
import Footer from "@/shared/ui/Footer";
import Header from "@/shared/ui/Header/Header";
import Head from "next/head";
import Link from "next/link";


export default function Home() {

  return (
    <>
      <Head>
        <title>furniture srore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
           <section className="b frr">
            <div className="container">
             <Header/>

             <div className="header_posit">
              <div className="hdr_left">

                <div className="logo">
                  <img src="./img/logo.png" alt="" />
                </div>

                <div className="hdr_l_1">
                  <p className="txt_2">Наши производители</p>
                  <div className="pht">
                    <img src="./img/pht.png" alt="" />
                  </div>

                  <div className="line"></div>
                </div>

                <div className="pht_2">
                  <img src="./img/pht2.png" alt="" />
                </div>

                <div className="pht_3">
                  <img src="./img/pht3.png" alt="" />
                </div>
              </div>

              <button className="btn">
                <img src="./img/crt.png" alt="cart" />
              </button>
             </div>

              <div className="banner">
                 <div className="bnr_itm">
                  <ul className="banner_ul">
                    <li className="ll">
                      <div className="li_icn">
                        <img src="./img/Sheets.png" alt="" />
                      </div>
                      <Link href="#" className="lnk_1">
                            Матрасы
                      </Link>
                    </li>

                     <li className="ll">
                      <div className="li_icn">
                        <img src="./img/Pillow.png" alt="" />
                      </div>
                      <Link href="#" className="lnk_1">
                            Подушки
                      </Link>
                    </li>

                    <li className="ll">
                      <div className="li_icn">
                        <img src="./img/Bedroom.png" alt="" />
                      </div>
                      <Link href="#" className="lnk_1">
                            Спальня
                      </Link>
                    </li>

                    <li className="ll">
                      <div className="li_icn">
                        <img src="./img/shts.png" alt="" />
                      </div>
                      <Link href="#" className="lnk_1">
                            Топеры
                      </Link>
                    </li>

                    <li className="ll">
                      <div className="li_icn">
                        <img src="./img/Blankie.png" alt="" />
                      </div>
                      <Link href="#" className="lnk_1">
                            Аксесуары
                      </Link>
                    </li>

                    <li className="ll">
                      <div className="li_icn">
                        <img src="./img/Baby.png" alt="" />
                      </div>
                      <Link href="#" className="lnk_1">
                            Детям
                      </Link>
                    </li>
                  </ul>
                    
                   <div className="bnr_bottom">
                    <div className="bnr_left">
                      <p className="txt_3">
                        Матрас Monday   <br />
                        80 х 200 
                      </p>

                      <ul className="ul_3">
                        <li>
                          <div className="plcn">
                            <img src="./img/Polygon.png" alt="" />
                          </div>
                          Независимый блок «ТFK 5 Zone»
                          </li>

                        <li>
                          <div className="plcn">
                            <img src="./img/Polygon.png" alt="" />
                          </div>
                           Максимальная нагрузка – 140 кг
                          </li>

                        <li>
                          <div className="plcn">
                            <img src="./img/Polygon.png" alt="" />
                          </div>
                          Высота матраса - 20 см
                          </li>
                      </ul>

                         <p className="txt_4">
                          15 750 ₽ 
                         </p>

                         <div className="bnr_txt">
                          <p className="txt_5">
                            ВСЕГО ЗА
                          </p>

                          <p className="txt_6">
                            ВСЕГО ЗА
                          </p>
                         </div>
                    </div>

                    <div className="bnr_rigth">
                    <img src="./img/br.png" alt="" />
                   </div>
                   </div>

                   
                 </div>

              </div>
            </div>
           </section>

           <section className="bcgr">
            <div className="container">
              <Armchairs/>
            </div>
           </section>

           <section className="mbl_back">
            <div className="container">
              <div className="mebelo_block">
                <div className="mbl_left">
                  <img src="./img/mbl.png" alt="" />
                </div>

               <div className="mbl_rigth">
                 <p className="txt_11">
                  Mebello - особенный салон мебели <br />
                  в Туле
                 </p>


                 <p className="txt_12">
                  Салон Mebello - не просто магазин мебели на любой вкус. Здесь <br />
                  представлина шировая линейка производителей на любой вкус. <br />
                  Наши основные преимущества. Далее описательный текст на <br />
                  несколько абзацев. <br />
                  Салон Mebello - не просто магазин мебели на любой вкус. Здесь <br />
                  представлина шировая линейка производителей на любой вкус. <br />
                  Наши основные преимущества. Далее описательный текст на <br />
                  несколько абзацев. Салон Mebello - не просто магазин мебели на <br />
                  любой вкус. Здесь представлина шировая линейка  <br />производителей на любой вкус. Наши основные преимущества. <br />
                  Далее описательный текст на несколько абзацев.
                 </p>
               </div>
              </div>
            </div>
           </section>

           <section className="mbl_ba">
            <div className="container">
              <div className="mebels_block">
                 <div className="mebels_lft">
                  <p className="txt_13">
                    Не нашли того, <br />
                    что искали?
                  </p>

                  <p className="txt_14">Оставьте свой номер и мы подберём для Вас всё, что нужно.</p>

              <form action="#">
                <div className="frm_b">
                      <div className="inp_tl">
                      <input type="tel" name="" id="" placeholder="Телефон" />
                     </div>

                     <button className="btn_2">
                      ОТПРАВИТЬ
                     </button>
                    
                  </div>
              </form>
                 </div>

                 <div className="mebels_ri">
                  <img src="./img/mbbb.png" alt="" />
                 </div>
              </div>
            </div>
           </section>

           <section className="frr">
            <div className="container">
              <div className="reviews_block">
                 <p className="txt_15">ОТЗЫВЫ</p>

                 <div className="reviewa_grid">
                   <div className="rev_itm">
                     
                   </div>
                 </div>
              </div>
            </div>
           </section>

           <section className="frr">
            <div className="container">
            <Cart/>
            </div>
           </section>

           <section className="frr">
            <div className="container">
              <Footer/>
            </div>
           </section>
        </main>
      </div>
    </>
  );
}
